name = "utilitybot-misc-backends"
type = "javascript"
workers_dev = true
compatibility_date = "2022-01-26"
account_id = "a16c46903e48ca62bccffe417a00c7c6"

kv_namespaces = [ 
  { binding = "rolenames", preview_id = "e6d7f19863e94b28bf27157c4821dbe6", id = "a1058cda195244f7a80d01d15afc633c" }
]

[vars]
WORKERS_RS_VERSION = "0.0.7"

[build]
command = "cargo install -q worker-build && worker-build --release" # required

[build.upload]
dir    = "build/worker"
format = "modules"
main   = "./shim.mjs"

[[build.upload.rules]]
globs = ["**/*.wasm"]
type  = "CompiledWasm"

# read more about configuring your Worker via wrangler.toml at:
# https://developers.cloudflare.com/workers/cli-wrangler/configuration
