name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      CF_EMAIL: ${{ secrets.CF_EMAIL }}
      CF_API_KEY: ${{ secrets.CF_API_TOKEN }}
    name: Deploy
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo install wrangler && wrangler publish
